/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlService = IDL.Service({
  'getAllContacts' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'name' : IDL.Text,
            'email' : IDL.Text,
            'message' : IDL.Text,
            'phone' : IDL.Opt(IDL.Text),
          })
        ),
      ],
      ['query'],
    ),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  return IDL.Service({
    'getAllContacts' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'name' : IDL.Text,
              'email' : IDL.Text,
              'message' : IDL.Text,
              'phone' : IDL.Opt(IDL.Text),
            })
          ),
        ],
        ['query'],
      ),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };